### PR TITLE
NPM Support and index.js

### PR DESCRIPTION
**Pull request by tim-smart**
Should be all ready for a `npm publish`. Also added a index.js in the root so you can directly `git clone` the repo into .node_libraries.

### CODE REVIEW

**Comment by bnoguchi** [comment]
Tim, thanks for thinking about this. Just got back from a vacation, but I'll take a close tomorrow. I was working on a package.json builder for the console built in ruby and was going to generate the package.json for the redis module once it was done. Incidentally, I also received a prior npm patch pull request while on vacation. I'll give both pull requests a complete review tomorrow and merge/publish it until I get my npm package.json builder in a releasable condition. I was also thinking of just naming the module "redis" vs "redis-node" on the npm registry :) Thanks!
--Brian

**Comment by tim-smart** [comment]
"redis" is already taken :)

**Comment by bnoguchi** [comment]
Cool, just added your name to the list of contributors. Thanks!

By the way, I haven't taken a complete look at the "redis" npm module. How does it stack up to this one?

--Brian

**Comment by tim-smart** [comment]
I'm not sure. It completely blows the pants off redis-node-client in terms of performance, but I don't think anyone has benched it against your library yet.

In terms of complete-ness, it also has transactional support and publish/subscribe, so roughly on even terms there. Take a look I guess: http://github.com/mranney/node_redis

**Pull request closed without merging**
